# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: catpi_api
  password: <%= ENV['CATPI_API_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: catpi_api_development


test:
  <<: *default
  host: localhost
  database: catpi_api_test

production:
  <<: *default
  host: localhost
  database: catpi_api_production